COPY_EXISTING_REGEXP GLOB ~^.*\.itm$~ ~override~
  READ_SHORT ITM_type type
  READ_SHORT ITM_stack_amount stack
  READ_LONG ITM_weight weight
  PATCH_MATCH type WITH
    ITEM_TYPE_dart ITEM_TYPE_axe ITEM_TYPE_dagger WHEN stack > 1
    BEGIN
      WRITE_LONG ITM_weight 0
    END
    DEFAULT
  END
BUT_ONLY

ACTION_IF (FILE_EXISTS_IN_GAME ~j#janbol.itm~) BEGIN
  COPY_EXISTING ~j#janbol.itm~ ~override~
    WRITE_LONG ITM_weight 0
  BUT_ONLY
END
