# yaml-language-server: $schema=https://raw.githubusercontent.com/BGforgeNet/bgforge.yml/refs/heads/main/schema.json

translation:
  tra_dir: tnt/tra

golem:
  mod_dir: tnt
  platforms:
    - eet
    - bgt
    - sod
    - bg2ee
    - bgee
    - tob
  happy: true

mls:
  translation:
    directory: tnt/tra/english
