COPY_EXISTING ~clck26.itm~   ~override~
  //deleting area spell immunities if any
  LPF DELETE_ITEM_EQEFFECT
    INT_VAR
      opcode_to_delete = OPCODE_protection_from_spell
  END

  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = OPCODE_protection_from_spell //spell immunity
      target = TARGET_FEATURE_self
      timing = TIMING_while_equipped
    STR_VAR
      resource = ~sppr302~
  END
BUT_ONLY
