ACTION_IF FILE_EXISTS_IN_GAME ~m#amber.bcs~ BEGIN
  COPY_EXISTING ~m#amber.bcs~ ~override~

    DECOMPILE_AND_PATCH BEGIN
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("M#AmberJaheiraRomanceConflict","GLOBAL",0)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("M#AmberAerieRomanceConflict","GLOBAL",0)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("M#AmberViconiaRomanceConflict","GLOBAL",0)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("M#AmberSolaRomanceConflict","GLOBAL",0)~
        ~ False()~

      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("M#AmIUsingMultiRomanceScript","Locals",10)~
        ~ False()~

      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("AerieRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("JaheiraRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("ViconiaRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ GlobalGT("SolaTalk","GLOBAL",13)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("KiaraRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("E3FadeRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("imoenromanceactive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("SaerilethRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("TashiaRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("SimeRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("NathRomanceActive","GLOBAL",2)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("AnomenRomanceActive","GLOBAL",2)~
        ~ False()~

    END
  BUT_ONLY
END

<<<<<<<< .../tnt-inlined/romance_cheats/amber_old1.baf
IF
  Global("M#AmberMatch","GLOBAL",0)
  Gender(Player1,MALE)
  CheckStatGT(Player1,11,CHR)
  CheckStatGT(Player1,11,INT)
THEN 
  RESPONSE #100
    SetGlobal("M#AmberMatch","GLOBAL",1)
END
>>>>>>>>
<<<<<<<< .../tnt-inlined/romance_cheats/amber_new1.baf
IF
  Global("M#AmberMatch","GLOBAL",0)
THEN 
  RESPONSE #100
    SetGlobal("M#AmberMatch","GLOBAL",1)
END
>>>>>>>>
COPY_EXISTING ~baldur.bcs~ ~override~
  R_B_B CASE_INSENSITIVE
    ~.../tnt-inlined/romance_cheats/amber_old1.baf~
    ~.../tnt-inlined/romance_cheats/amber_new1.baf~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
      ~ Global("M#AmberRomanceOut","GLOBAL",0)~
      ~ False()~
  END
BUT_ONLY
