<<<<<<<< .../tnt-inlined/romance_cheats/tyris_match_old.baf
IF
  Global("G#TF.TyrisMatch","GLOBAL",0)
  Global("G#TF.CheckTyrisMatch","GLOBAL",0)
  Gender(Player1,MALE)
  OR(3)
    Race(Player1,HUMAN)
    Race(Player1,HALF_ELF)
    Race(Player1,ELF)
THEN
  RESPONSE #1
    SetGlobal("G#TF.CheckTyrisMatch","GLOBAL",1)
    SetGlobal("G#TF.TyrisMatch","GLOBAL",1)
END

IF
  Global("G#TF.TyrisMatch","GLOBAL",0)
  Global("G#TF.CheckTyrisMatch","GLOBAL",0)
THEN
  RESPONSE #1
    SetGlobal("G#TF.CheckTyrisMatch","GLOBAL",1)
END
>>>>>>>>
<<<<<<<< .../tnt-inlined/romance_cheats/tyris_match_new.baf
IF
  Global("G#TF.CheckTyrisMatch","GLOBAL",0)
THEN
  RESPONSE #1
    SetGlobal("G#TF.CheckTyrisMatch","GLOBAL",1)
END

IF
  Global("G#TF.TyrisMatch","GLOBAL",0)
THEN
  RESPONSE #1
    SetGlobal("G#TF.TyrisMatch","GLOBAL",1)
END
>>>>>>>>

COPY_EXISTING ~baldur.bcs~ ~override~
              ~baldur25.bcs~ ~override~
  R_B_B CASE_INSENSITIVE
    ~.../tnt-inlined/romance_cheats/tyris_match_old.baf~
    ~.../tnt-inlined/romance_cheats/tyris_match_new.baf~
BUT_ONLY

ACTION_FOR_EACH script IN
  aerie
  jaheira
  viconia
  dorn
  neera
BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.bcs~ AND FILE_EXISTS_IN_GAME ~g#tyris.bcs~) BEGIN
    COPY_EXISTING ~%script%.bcs~ ~override~

      DECOMPILE_AND_PATCH BEGIN
        REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
          ~ Global("G#TF.TyrisRomanceActive","GLOBAL",1)~
          ~ False()~
        REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
          ~ Global("G#TF.TyrisRomanceActive","GLOBAL",2)~
          ~ False()~
      END

    BUT_ONLY
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~g#tyris.bcs~ BEGIN
  COPY_EXISTING ~g#tyris.bcs~ ~override~

    DECOMPILE_AND_PATCH BEGIN

      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("AerieRomanceActive","GLOBAL",1)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("AerieRomanceActive","GLOBAL",2)~
        ~ False()~

      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("JaheiraRomanceActive","GLOBAL",1)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("JaheiraRomanceActive","GLOBAL",2)~
        ~ False()~

      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("ViconiaRomanceActive","GLOBAL",1)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("ViconiaRomanceActive","GLOBAL",2)~
        ~ False()~

      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("NeeraRomanceActive","GLOBAL",1)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("NeeraRomanceActive","GLOBAL",2)~
        ~ False()~

      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("DornRomanceActive","GLOBAL",1)~
        ~ False()~
      REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH
        ~ Global("DornRomanceActive","GLOBAL",2)~
        ~ False()~

    END
  BUT_ONLY
END
