// instant detection
IF
  Global("%trap_var_base%_detected", "MYAREA", 0)
  %is_active%
  %traps_baf_class%
  %traps_baf_range%
  !StateCheck(LastSeenBy, CD_STATE_NOTVALID)
  !CheckStatLT(LastSeenBy, %detection%, TRAPS)
  TriggerOverride(LastSeenBy, ModalState(DETECTTRAPS))
  ActionListEmpty()
THEN
	RESPONSE #1
    ReallyForceSpellRES("%trap_spl%", Myself)
    SetGlobal("%trap_var_base%_detected", "MYAREA", 1)
    Continue()
END
