//Clear empty strings with non-(-1) references
INCLUDE ~%MOD_FOLDER%/lib/soundsets/cre_list.tph~
INCLUDE ~%MOD_FOLDER%/extended_soundsets/clear_empty.tph~

//Read soundsets
INCLUDE ~%MOD_FOLDER%/extended_soundsets/read_soundsets.tph~

//Write them
INCLUDE ~%MOD_FOLDER%/extended_soundsets/write_soundsets.tph~

//Cherry pick some other lines, mostly battle cries
INCLUDE ~%MOD_FOLDER%/extended_soundsets/cherry_pick.tph~
