COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
    READ_SHORT (ab_off + 0x12) cast_time
    delay = (10 - cast_time) * 6 / 10
    LPF ADD_SPELL_EFFECT
      INT_VAR
        opcode = 1 //apr
        parameter1 = 0 //0 apr
        parameter2 = 1 //flat mod
        duration = delay
        target = 1 //self
        resist_dispel = 0 //non magical
        header = int
    END
//    PATCH_PRINT ~%SOURCE_FILE%: header %int%, casting time is %cast_time%, no attack time is %delay%~
  END
BUT_ONLY
