LAF list_web_spells RET_ARRAY web_spells = spells END

COPY_EXISTING ~plyspid.itm~  ~override~
  PHP_EACH web_spells AS index => spell BEGIN
    LPF ADD_ITEM_EQEFFECT
      INT_VAR
        opcode = OPCODE_protection_from_spell
        target = TARGET_FX_self
        timing = TIMING_while_equipped
        resist_dispel = BYPASS_MR
      STR_VAR
        resource = EVAL ~%spell%~
    END
  END
BUT_ONLY
