//dummy detection file
COPY_EXISTING ~sw1h01.itm~ ~override/g_tt_web.itm~
 
LAF list_web_spells RET_ARRAY web_spells = spells END

COPY_EXISTING ~plyspid.itm~  ~override~
  PHP_EACH web_spells AS index => spell BEGIN
    LPF ADD_ITEM_EQEFFECT
      INT_VAR
        opcode = 206 //spell immunity
        target = 1 //self
        timing = 2 //while equipped
        resist_dispel = 2 // no dispell, bypass res
      STR_VAR
        resource = EVAL ~%spell%~
    END
  END
BUT_ONLY
