COPY_EXISTING_REGEXP GLOB ~.*\.cre~ ~override~
  //here should be validity checks, but they're really, really long
  READ_ASCII DEATHVAR deathvar
  PATCH_IF FILE_CONTAINS_EVALUATED(~pdialog.2da~ ~%deathvar%~) BEGIN
    FOR (i = 44; i < 53; i = i + 1) BEGIN
      WRITE_LONG (CRE_soundset_start + i * 4) "-1"
    END
    //responses to compliments and insults
    FOR (i = 55; i < 61; i = i + 1) BEGIN
      WRITE_LONG (CRE_soundset_start + i * 4) "-1"
    END
  END
BUT_ONLY
