name: Poify/Unpoify
on:
  push:
    paths:
      - "tnt/tra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Poify/Unpoify
        uses: BGforgeNet/msg2po@dev
        with:
          poify: true
          unpoify: true
          push: true
          dir2msgstr: true
          single_commit: true

      - name: Handle charsets
        uses: BGforgeNet/handle-charsets@master
        with:
          tra_path: tnt/tra
          out_path: tnt/tra_ee
          from_utf8: false
          split_console: true
          commit: true
