on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  CreateIEModZipPackagesUploadToPublishedRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository using 'github.ref' from release
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create Infinity Engine Mod Packages (.iemod and .zip)
        uses: ALIENQuake/CreateIEModZipPackage@master
        id: CreateIEModZipPackage
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload iemod package to latest release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.CreateIEModZipPackage.outputs.PackageBaseName }}.iemod
          asset_name: ${{ steps.CreateIEModZipPackage.outputs.PackageBaseName }}.iemod
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload zip package to latest release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.CreateIEModZipPackage.outputs.PackageBaseName }}.zip
          asset_name: ${{ steps.CreateIEModZipPackage.outputs.PackageBaseName }}.zip
          tag: ${{ github.ref }}
          overwrite: true
