OUTER_TEXT_SPRINT comp_dir ~%components%/%comp_name%~

OUTER_TEXT_SPRINT spl_despin ~g_despin~
OUTER_TEXT_SPRINT icon ~%spl_despin%~
COPY ~%comp_dir%/%icon%.bam~ ~override~ //"cancel spin" ability icon

OUTER_TEXT_SPRINT sectype ~g_spin~
ADD_SECTYPE ~%sectype%~ @1
OUTER_SET sectype_id = g_spin  //set by ADD_SECTYPE

PRINT ~%spl_despin%.spl~
OUTER_TEXT_SPRINT test EVAL ~%spl_despin%.spl~
PRINT ~%test%~

// "cancel spin" ability
LAF CREATE_SPELL
  INT_VAR
    flags = FLAG_SPL_ignore_dead_wild_magic
    sectype = sectype_id
  STR_VAR spell = EVAL ~%spl_despin%.spl~
END
COPY_EXISTING ~%spl_despin%.spl~ override
  LPF ADD_SPELL_HEADER END
  LPF ADD_SPELL_EFFECT //remove active spins
    INT_VAR
      opcode = OPCODE_remove_secondary_type
      parameter1 = 1 //max level
      paremeter2 = sectype_id
      timing = TIMING_permanent
  END
  LPF ADD_SPELL_EFFECT //remove self
    INT_VAR
      opcode = OPCODE_remove_spell
      timing = TIMING_permanent
    STR_VAR resource = ~%spl_despin%~
  END
  WRITE_ASCIIT SPL_icon ~%icon%~
BUT_ONLY

ACTION_FOR_EACH spl IN BLADE_OFFENSIVE_SPIN BLADE_DEFENSIVE_SPIN BEGIN //spins
  COPY_EXISTING ~%spl%.spl~ override
    WRITE_BYTE SPL_sectype sectype_id
    LPF ADD_SPELL_EFFECT //remove active spins first
      INT_VAR
        opcode = OPCODE_remove_secondary_type
        parameter1 = 1 //max level
        paremeter2 = sectype_id
        timing = TIMING_permanent
        insert_point = 0
    END
    LPF ADD_SPELL_EFFECT //add "cancel spin" ability
      INT_VAR
        opcode = OPCODE_give_ability
        timing = TIMING_permanent
      STR_VAR resource = ~%spl_despin%~
    END
    LPF ADD_SPELL_EFFECT //remove "cancel spin" ability
      INT_VAR
        opcode = OPCODE_remove_spell
        timing = TIMING_delayed
        duration = 24
      STR_VAR resource = ~%spl_despin%~
    END
  BUT_ONLY
END
